#undef TAPPING_TERM
#define TAPPING_TERM 170

// #undef ONESHOT_TIMEOUT
// #define ONESHOT_TIMEOUT 1000

#define COMBO_TERM 60

#define USB_SUSPEND_WAKEUP_DELAY 0

#define CAPS_LOCK_STATUS
#define USB_POLLING_INTERVAL_MS 10
#define RAW_USAGE_PAGE 0xFF60
#define RAW_USAGE_ID 0x61
#define LAYER_STATE_8BIT
#define COMBO_COUNT 5

#define NO_AUTO_SHIFT_ALPHA
#define AUTO_SHIFT_TIMEOUT 135

#define LEADER_NO_TIMEOUT
#define LEADER_PER_KEY_TIMING
#define LEADER_TIMEOUT 250

#define TAPPING_TERM_PER_KEY
